# Generated by Django 3.0.11 on 2021-01-25 20:24

from django.db import migrations, models
import up_revendas.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210124_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(default='Conta corrente', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='cpf',
            field=models.CharField(default=1, max_length=14, validators=[up_revendas.users.validators.validate_CPF], verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(default='428.386.900-78', max_length=32),
            preserve_default=False,
        ),
    ]
