# Generated by Django 3.0.11 on 2021-01-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210122_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_store_manager',
            field=models.BooleanField(default=False),
        ),
    ]
