# Generated by Django 3.0.11 on 2021-01-23 12:21

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('hatch', 'Hatch'), ('sedan', 'Sedã'), ('suv', 'SUV'), ('van', 'Van/Utilitário'), ('pick-up', 'Pick-Up'), ('convertible', 'Conversível'), ('sport', 'Sport'), ('luxury', 'Luxo')], default='hatch', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('black', 'Preto'), ('white', 'Branco'), ('silver', 'Prata'), ('red', 'Vermelho'), ('cinza', 'Cinza'), ('blue', 'Azul'), ('yellow', 'Amarelo'), ('green', 'Verde'), ('orange', 'Laranja'), ('other', 'Outra')], default='silver', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=100, verbose_name=builtins.min),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic'), ('SA', 'Semi Automatic')], default='M', max_length=14),
            preserve_default=False,
        ),
    ]
